"""
Django settings for MyProject project.

Generated by 'django-admin startproject' using Django 5.2.4.
Updated for Render Deployment.
"""

from pathlib import Path
import os
import dj_database_url  # REQUIRED: You must install 'dj-database-url'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Checks for 'SECRET_KEY' in environment, falls back to insecure key for local dev only
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-gz+phx#0zcphjh_-)umnus&s^cz+x#+8bzb2olh*s=7lr0l*vg')

# SECURITY WARNING: don't run with debug turned on in production!
# If 'RENDER' is in the environment variables, Debug will be False.
DEBUG = 'RENDER' not in os.environ

ALLOWED_HOSTS = []

# Add Render's URL to allowed hosts automatically
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'MyApp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # REQUIRED: Added for static files on Render
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'middleware.block_middleware.BlockUserMiddleware'
]

ROOT_URLCONF = 'MyProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MyProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# This setup uses the 'DATABASE_URL' environment variable on Render.
# For local development, if you don't have that variable set, it falls back to 
# the explicit config (which you should keep secure).
DATABASES = {
    'default': dj_database_url.config(
        # Replace this string with your local connection string if running locally
        default=os.environ.get('DATABASE_URL', 'postgres://postgres:Sabirmhd@123@db.vzcqmbykfctdyeaxjutv.supabase.co:5432/postgres'),
        conn_max_age=600,
        ssl_require=True
    )
}

AUTH_USER_MODEL = 'MyApp.User'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# This is where collectstatic will put files for Render to serve
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Use Whitenoise to serve static files in production
if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/MyApp/login/'

# Email Settings
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "sabirmhd30@gmail.com"

# SECURITY: Read from Environment Variable
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD') 

DEFAULT_FROM_EMAIL = "TurfZone <sabirmhd30@gmail.com>"
RAZORPAY_KEY_ID = "rzp_test_RFRn81LF4xVnHS"

# SECURITY: Read from Environment Variable
RAZORPAY_KEY_SECRET = os.environ.get('RAZORPAY_KEY_SECRET')