# Generated by Django 5.2.4 on 2025-07-31 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('parking', 'Parking'), ('lights', 'Flood Lights'), ('locker', 'Locker Room'), ('refreshments', 'Refreshments'), ('washroom', 'Washroom'), ('seating', 'Spectator Seating')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turf_name', models.CharField(max_length=100)),
                ('sport_type', models.CharField(choices=[('football', 'Football'), ('cricket', 'Cricket'), ('badminton', 'Badminton'), ('tennis', 'Tennis'), ('multi', 'Multi-sport')], max_length=50)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=10)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=6)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='turf_images/')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facilities', models.ManyToManyField(blank=True, to='MyApp.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turfs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
