# Generated by Django 5.2.4 on 2025-08-02 08:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_facility_turf'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
