# Generated by Django 5.2.4 on 2025-08-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_turfbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf',
            name='price_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
