# Generated by Django 5.2.4 on 2025-08-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_alter_turf_price_per_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
            preserve_default=False,
        ),
    ]
