# Generated by Django 5.2.4 on 2025-08-13 14:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_alter_turf_price_per_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7),
        ),
    ]
