# Generated by Django 5.2.4 on 2025-08-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_alter_turf_price_per_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf',
            name='price_per_hour',
            field=models.IntegerField(),
        ),
    ]
