# Generated by Django 4.2.27 on 2026-01-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0014_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='player', max_length=20),
        ),
    ]
